
package lab3;

import nrc.fuzzy.*;

/**
*
* @author Gonzalom
*/
public class Interfaz extends javax.swing.JFrame {

	/**
	* Creates new form Interfaz
	*/
	public Interfaz() {
		initComponents();
	}

	/**
	* This method is called from within the constructor to initialize the form.
	* WARNING: Do NOT modify this code. The content of this method is always
	* regenerated by the Form Editor.
	*/
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        barraConsumo = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barraComportamiento = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        barraIntentos = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        barraTraumas = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        barraAprecio = new javax.swing.JSlider();
        botonDiagnostico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarInferencia = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        infoConsumo = new javax.swing.JButton();
        infoComportamiento = new javax.swing.JButton();
        infoSuicida = new javax.swing.JButton();
        infoTraumas = new javax.swing.JButton();
        infoTraumas1 = new javax.swing.JButton();

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("?");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diagnostico de Riesgo Suicida");

        barraConsumo.setMajorTickSpacing(5);
        barraConsumo.setMaximum(60);
        barraConsumo.setMinorTickSpacing(5);
        barraConsumo.setPaintLabels(true);
        barraConsumo.setPaintTicks(true);
        barraConsumo.setToolTipText("");
        barraConsumo.setValue(0);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Habitualidad en el consumo de alcohol");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cambios en el comportamiento y estado de animo");

        barraComportamiento.setMajorTickSpacing(1);
        barraComportamiento.setMaximum(10);
        barraComportamiento.setPaintLabels(true);
        barraComportamiento.setPaintTicks(true);
        barraComportamiento.setValue(0);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Planificación suicida y/o autoflagelaciones");

        barraIntentos.setMajorTickSpacing(1);
        barraIntentos.setMaximum(10);
        barraIntentos.setMinorTickSpacing(1);
        barraIntentos.setPaintLabels(true);
        barraIntentos.setPaintTicks(true);
        barraIntentos.setValue(0);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Existencia de traumas y/o preocupaciones");

        barraTraumas.setMajorTickSpacing(1);
        barraTraumas.setMaximum(10);
        barraTraumas.setPaintLabels(true);
        barraTraumas.setPaintTicks(true);
        barraTraumas.setValue(0);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Percepcion de utilidad para la sociedad");

        barraAprecio.setMajorTickSpacing(1);
        barraAprecio.setMaximum(10);
        barraAprecio.setMinorTickSpacing(1);
        barraAprecio.setPaintLabels(true);
        barraAprecio.setPaintTicks(true);
        barraAprecio.setValue(0);

        botonDiagnostico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonDiagnostico.setText("Diagnosticar");
        botonDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDiagnosticoActionPerformed(evt);
            }
        });

        mostrarInferencia.setColumns(20);
        mostrarInferencia.setRows(5);
        jScrollPane1.setViewportView(mostrarInferencia);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Software diseñado para encontrar el nivel de riesgo suicida de un paciente.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Ingrese el nivel del paciente en cada una de las siguientes variables");

        infoConsumo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoConsumo.setText("?");
        infoConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoConsumoActionPerformed(evt);
            }
        });

        infoComportamiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoComportamiento.setText("?");
        infoComportamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoComportamientoActionPerformed(evt);
            }
        });

        infoSuicida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoSuicida.setText("?");
        infoSuicida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoSuicidaActionPerformed(evt);
            }
        });

        infoTraumas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoTraumas.setText("?");
        infoTraumas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoTraumasActionPerformed(evt);
            }
        });

        infoTraumas1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoTraumas1.setText("?");
        infoTraumas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoTraumas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(infoConsumo)
                            .addComponent(barraConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(barraComportamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(infoComportamiento))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(infoSuicida))
                            .addComponent(barraIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(infoTraumas))
                            .addComponent(barraTraumas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoTraumas1))
                            .addComponent(barraAprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addComponent(botonDiagnostico)
                        .addGap(113, 113, 113)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(infoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoComportamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barraConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraComportamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoSuicida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoTraumas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barraIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barraTraumas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoTraumas1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(barraAprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonDiagnostico)
                        .addGap(203, 203, 203))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDiagnosticoActionPerformed
                
    // Obtenemos los valores de las barras
    float consumo            = barraConsumo       .getValue();
    float comportamiento     = barraComportamiento.getValue();
    float intentos_suicidios = barraIntentos      .getValue();
    float traumas            = barraTraumas       .getValue();
    float aprecio            = barraAprecio       .getValue();

    try{

        reglasDifusas reglas;
        reglas = new reglasDifusas(new conjuntosDifusos());
        mostrarInferencia.setText(reglas.obtenerExplicacion(consumo, comportamiento, intentos_suicidios, traumas, aprecio));


    }catch(FuzzyException e){
        // Ocurrio un error en la libreria de logica difusa
        mostrarInferencia.setText("Error en la libreria de lógica difusa");
        System.out.println(e);
    }
        
        
        
        
    }//GEN-LAST:event_botonDiagnosticoActionPerformed

    private void infoConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoConsumoActionPerformed
        // TODO add your handling code here:
        mostrarInferencia.setText("-INFORMACION DE "+" HABITUALIDAD EN EL CONSUMO DE ALCOHOL"+"\n\n");
        mostrarInferencia.append("\tMEDIDA: "+"Dias"+"\n\n");
        mostrarInferencia.append("\tIngrese cada cuantos dias el paciente tiende a consumir alcohol"+"\n");
    }//GEN-LAST:event_infoConsumoActionPerformed

    private void infoComportamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoComportamientoActionPerformed
        // TODO add your handling code here:
        mostrarInferencia.setText("-INFORMACION DE "+" CAMBIOS DE COMPORTAMIENTO"+"\n\n");
        mostrarInferencia.append("\tMEDIDA: "+"Escala de percepcion"+"\n\n");
        mostrarInferencia.append("\tIngrese la percepcion que se tiene del paciene con respecto al grado que presenta en cambios\n");
        mostrarInferencia.append("\tde comportamiento y estados de animo, tendiendo al aislamiento social y la bipolaridad"+"\n");        
    }//GEN-LAST:event_infoComportamientoActionPerformed

    private void infoSuicidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoSuicidaActionPerformed
        // TODO add your handling code here:
        mostrarInferencia.setText("-INFORMACION DE "+" PLANIFICACION SUICIDA"+"\n\n");
        mostrarInferencia.append("\tMEDIDA: "+"Escala de percepcion"+"\n\n");
        mostrarInferencia.append("\tIngrese el grado que el paciente tiene de señalar su intención de suicidarse y/o el"+"\n");        
        mostrarInferencia.append("\tgrado en hacerse daño fisico (autoflagelaciones)."+"\n");                        
    }//GEN-LAST:event_infoSuicidaActionPerformed

    private void infoTraumasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoTraumasActionPerformed
        // TODO add your handling code here:
        mostrarInferencia.setText("-INFORMACION DE "+" TRAUMAS Y PREOCUPACIONES"+"\n\n");
        mostrarInferencia.append("\tMEDIDA: "+"Escala de percepcion"+"\n\n");
        mostrarInferencia.append("\tIngrese de una escala de 0 a 10, el grado de sufrimiento que tiene el paciente por"+"\n");        
        mostrarInferencia.append("\ttraumas y/o preocupaciones en su vida"+"\n");                        
    }//GEN-LAST:event_infoTraumasActionPerformed

    private void infoTraumas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoTraumas1ActionPerformed
        // TODO add your handling code here:
        mostrarInferencia.setText("-INFORMACION DE "+" PERCEPCION DE UTILIDAD PARA LA SOCIEDAD"+"\n\n");
        mostrarInferencia.append("\tMEDIDA: "+"Escala de percepcion"+"\n\n");
        mostrarInferencia.append("\tIngrese de una escala de 0 a 10, el grado en el que el paciente se siente util"+"\n");        
        mostrarInferencia.append("\tpara la sociedad y sus cercanos (autoestima)"+"\n");                                        
    }//GEN-LAST:event_infoTraumas1ActionPerformed

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		*/
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Interfaz().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider barraAprecio;
    private javax.swing.JSlider barraComportamiento;
    private javax.swing.JSlider barraConsumo;
    private javax.swing.JSlider barraIntentos;
    private javax.swing.JSlider barraTraumas;
    private javax.swing.JButton botonDiagnostico;
    private javax.swing.JButton infoComportamiento;
    private javax.swing.JButton infoConsumo;
    private javax.swing.JButton infoSuicida;
    private javax.swing.JButton infoTraumas;
    private javax.swing.JButton infoTraumas1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mostrarInferencia;
    // End of variables declaration//GEN-END:variables
}
